name: Metrics
on:
  # Chạy mỗi 24h
  schedule: [{cron: "0 0 * * *"}]
  # Chạy thủ công
  workflow_dispatch:
  # Chạy khi push code
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Token của bạn (Mặc định Github sẽ tự hiểu)
          token: ${{ secrets.GITHUB_TOKEN }}

          # Cấu hình người dùng
          user: LTB122
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Ho_Chi_Minh
          
          # Plugin: Ngôn ngữ chi tiết
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css
          plugin_languages_details: bytes-size, percentage
          
          # Plugin: Thói quen code (Sáng/Trưa/Chiều/Tối)
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          
          # Plugin: Lịch isometric (Giống cái 3D)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year